
services:
  neo4j_luna:
    image: neo4j:5.12
    container_name: neo4j_luna
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=neo4j/password  
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.meta.data,apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      # - neo4j_config:/config
      - neo4j_plugin:/plugins

  python-app:
    build:
      context: .  
    container_name: python-app
    depends_on:
      - neo4j_luna
    environment:
      - OPENAI_API_KEY=xxx
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    ports:
      - "8000:8000"  

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugin: